### ISSUE TITLE
DB: DatabaseWriter - interaction between DB and UI

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/hornherzogen#35]
Provide basic setup
* [ ] Testability of PDO -> open how this works with the old version (work in progress)
* [x] Baseclass with healthy/connection
* [x] SQLite in test mode
* https://github.com/sebastianbergmann/dbunit/tree/2.0/samples/BankAccountDB
* a more modern version: https://phpunit.de/manual/current/en/database.html

DatabaseWriter is supposed to (via subclassing):
* [ ] persist new applicants #50 
* [ ] search for applicants by given firstname, lastname and email (to verify and hinder double posting #36) #50 
* [ ] generate a combinedName in case an applicant with the same firstname, lastname combination does exist in the database #50 
* [ ] show lists of applicants per week #50 
* [ ] show list of applicants per week / all applicants #50 
* [ ] manage room bookings #51
* [ ] show lists of bookings per week #51
